import { ReportNotice, ReportTable, SourceBadge } from "@/components/admin/analytics/analytics-ui";
import { analyticsDays, PeriodControls } from "@/components/admin/analytics/period-controls";
import { RefreshReportButton } from "@/components/admin/analytics/refresh-button";
import styles from "@/components/admin/analytics/analytics.module.css";
import { AdminPageHeader } from "@/components/admin/admin-ui";
import { getBehaviorReport } from "@/lib/analytics/google-data";
import { getInternalAnalyticsReport } from "@/lib/analytics/internal-reports";

export default async function BehaviorPage({searchParams}:{searchParams:Promise<{dias?:string}>}){const days=analyticsDays((await searchParams).dias);const[google,internal]=await Promise.all([getBehaviorReport(days),getInternalAnalyticsReport(days)]);return <div className={styles.stack}><AdminPageHeader eyebrow="Analytics" title="Comportamento" description="Páginas e navegação pelo Google; escolhas contextuais pelos dados internos."/><div className={styles.toolbar}><PeriodControls basePath="/admin/analytics/comportamento" days={days}/><RefreshReportButton area="behavior"/></div>{google.error?<ReportNotice source="Google Analytics">{google.error}</ReportNotice>:null}{internal.error?<ReportNotice source="Dados internos">{internal.error}</ReportNotice>:null}<div className={styles.compactGrid}><section className={styles.section}><SourceBadge>Google Analytics</SourceBadge><h2>Páginas mais vistas</h2><ReportTable label="Páginas mais vistas"><thead><tr><th>Página</th><th>Views</th><th>Usuários</th></tr></thead><tbody>{(google.data?.pages??[]).map(row=><tr key={row.path}><td>{row.path}</td><td>{row.views}</td><td>{row.users}</td></tr>)}</tbody></ReportTable></section><section className={styles.section}><SourceBadge>Dados internos</SourceBadge><h2>Filtros utilizados</h2><ReportTable label="Filtros utilizados"><thead><tr><th>Filtro</th><th>Valor</th><th>Usos</th></tr></thead><tbody>{internal.data.filters.map(row=><tr key={`${row.filterName}-${row.filterValue}`}><td>{row.filterName}</td><td>{row.filterValue}</td><td>{row.uses}</td></tr>)}</tbody></ReportTable></section></div><section className={styles.section}><SourceBadge>Dados internos</SourceBadge><h2>Links e ações externas</h2><ReportTable label="Ações externas"><thead><tr><th>Evento</th><th>Cliques</th></tr></thead><tbody>{internal.data.external.map(row=><tr key={row.eventName}><td>{row.eventName}</td><td>{row.clicks}</td></tr>)}</tbody></ReportTable></section><section className={styles.section}><SourceBadge>Google Analytics</SourceBadge><h2>Eventos no navegador</h2><ReportTable label="Eventos Google"><thead><tr><th>Evento</th><th>Ocorrências</th><th>Usuários</th></tr></thead><tbody>{(google.data?.events??[]).map(row=><tr key={row.eventName}><td>{row.eventName}</td><td>{row.count}</td><td>{row.users}</td></tr>)}</tbody></ReportTable></section></div>}
